version: "3.8"
services:
  app:
    container_name: bee_market_release
    image: won4885/bee_market_release:latest
    ports:
      - 8080:8080
    volumes:
      - bee_market_release:/app
  web:
    container_name: bee_market_release
    image: won4885/bee_market_release:latest
    ports:
      - 5173:5173
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - app
volumes:
  bee_market_release:
