version: "3.8"
services:
  app:
    container_name: bee_market_app_release
    image: won4885/bee_market_app_release:latest
    ports:
      - 8080:8080
    volumes:
      - bee_market_app_release:/app
  web:
    container_name: bee_market_web_release
    image: won4885/bee_market_web_release:latest
    ports:
      - 5173:5173
    depends_on:
      - app
volumes:
  bee_market_app_release:
