# syntax=docker/dockerfile:1
FROM node:18-alpine as web
WORKDIR /app
COPY . .

RUN npm install

RUN npm run build

FROM nginx
COPY ./nginx-release.conf /etc/nginx/nginx.conf
COPY --from-web /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
