FROM openjdk:17
WORKDIR /server
COPY . .
ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=release","-Dserver.port=8080","-Duser.timezone=Asia/Seoul","-jar","app.jar"]
